training:
  lr: 0.001
  weight_decay: 0.001
  n_epochs: 1200
  patience_reduce_lr: 100 # need to be divisible by "n_epochs_val" below
  cooldown: 130
  patience_end_training: 250 #same
  min_lr: 0.00001
  batch_size: 1

val:
  batch_size: 4
  n_epochs_val: 5

loss: MSE_loss