training:
  lr: 0.001
  weight_decay: 0.001
  n_epochs: 500
  patience_reduce_lr: 30 # need to be divisible by "n_epochs_val" below
  cooldown: 35
  patience_end_training: 50 #same
  min_lr: 0.00001
  batch_size: 1

val:
  batch_size: 4
  n_epochs_val: 1

loss: MSE_loss